version: '3.8'

services:

  postgres:
    image: postgres:16
    container_name: taskflow-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend-api:
    build:
      context: ./backend-api/TaskFlow.Api
      dockerfile: Dockerfile
    container_name: taskflow-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=taskflow-api
      - Jwt__Audience=taskflow-app
    ports:
      - "5000:8080"
    depends_on:
      - postgres

  notification-service:
    build: ./notification-service
    container_name: taskflow-notifications
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - BACKEND_API_URL=http://backend-api:8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    image: nginx:alpine
    container_name: taskflow-frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html

volumes:
  postgres_data: