@TaskFlow.Api_HostAddress = http://localhost:5000

### Register
POST {{TaskFlow.Api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "name": "Teste User",
  "email": "teste@taskflow.com",
  "password": "Senha123"
}

### Login
POST {{TaskFlow.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "teste@taskflow.com",
  "password": "Senha123"
}

### Get Tasks
GET {{TaskFlow.Api_HostAddress}}/api/tasks
Accept: application/json
Authorization: Bearer SEU_TOKEN_AQUI